### ISSUE TITLE
[Bug] 33% of course builds are failing

### ISSUE THREAD

**Issue by rachmari** [skills/configure-codeql-language-matrix#2]
### Summary

The [skills dashboard](https://dataexplorer.azure.com/dashboards/8ad8e3aa-6e34-48fa-a1c9-d91ced445d06?p-_startTime=30days&p-_endTime=now#a3665cce-6eea-40f9-8bf5-03f064d2061a) is reporting that 33% of the `configure-codeql-language-matrix` builds are failing:

![Image](https://github.com/user-attachments/assets/8861a569-0297-40b0-9dcf-d222a87d21bc)

### How to reproduce

1. Go to[ '...'](https://dataexplorer.azure.com/dashboards/8ad8e3aa-6e34-48fa-a1c9-d91ced445d06?p-_startTime=30days&p-_endTime=now#a3665cce-6eea-40f9-8bf5-03f064d2061a)
2. View the tile "Workflow builds"
3. Scroll down to `configure-codeql-language-matrix`
4. See failure rate

### Additional context

N/A

**Comment by hectorsector** [comment]
@camihmerhar @a-a-ron is this course published yet? In https://github.com/github/skills/issues/165#issuecomment-2205818889 it looks like we're still waiting for some content changes to be introduced.

**Comment by rachmari** [comment]
I read the numbers in the dashboard wrong. It's not 100% failures, it's 33%. Regardless, this is a new unpublished course, I'm going to close this out.
